"""edit_user__is_email_verified

Revision ID: 172085044088
Revises: 91ef4a9ecc70
Create Date: 2025-01-08 21:45:23.622608

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "172085044088"
down_revision: Union[str, None] = "91ef4a9ecc70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person", sa.Column("is_email_verified", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("person", "is_email_verified")
    # ### end Alembic commands ###
