"""init

Revision ID: b9e7eafcdcb2
Revises:
Create Date: 2025-01-03 19:18:32.365796

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9e7eafcdcb2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_index(op.f("ix_category_category_id"), "category", ["category_id"], unique=False)
    op.create_table(
        "channel",
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("members_cnt", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("is_personal", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    op.create_table(
        "person",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("referrer_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=20), nullable=True),
        sa.Column("telephone", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=182), nullable=False),
        sa.Column("firstname", sa.String(length=20), nullable=False),
        sa.Column("patronymic", sa.String(length=20), nullable=True),
        sa.Column("surname", sa.String(length=20), nullable=False),
        sa.Column("other_names", sa.String(length=256), nullable=True),
        sa.Column("gender", sa.Enum("male", "female", name="gender"), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("confidentiality", sa.Integer(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["person.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("telephone"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "channel_member",
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date_of_join", sa.DateTime(timezone=True), nullable=True),
        sa.Column("permissions", sa.Integer(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("notify_about_meeting", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id", "user_id"],
            ["channel_member.channel_id", "channel_member.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.channel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["person.user_id"],
        ),
        sa.PrimaryKeyConstraint("channel_id", "user_id"),
    )
    op.create_table(
        "favorite_category",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.category_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["person.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "category_id"),
    )
    op.create_table(
        "meeting",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_in_minutes", sa.Integer(), nullable=True),
        sa.Column("address", sa.String(length=512), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("minimum_age", sa.Integer(), nullable=True),
        sa.Column("maximum_age", sa.Integer(), nullable=True),
        sa.Column("only_for_itmo_students", sa.Boolean(), nullable=False),
        sa.Column("only_for_russians", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.channel_id"],
        ),
        sa.PrimaryKeyConstraint("meeting_id"),
    )
    op.create_table(
        "feedback",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.meeting_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["person.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "meeting_id"),
    )
    op.create_table(
        "meeting_category",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.category_id"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.meeting_id"],
        ),
        sa.PrimaryKeyConstraint("meeting_id", "category_id"),
    )
    op.create_table(
        "meeting_member",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date_of_join", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.meeting_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["person.user_id"],
        ),
        sa.PrimaryKeyConstraint("meeting_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meeting_member")
    op.drop_table("meeting_category")
    op.drop_table("feedback")
    op.drop_table("meeting")
    op.drop_table("favorite_category")
    op.drop_table("channel_member")
    op.drop_table("person")
    op.drop_table("channel")
    op.drop_index(op.f("ix_category_category_id"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
